# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get current date
      id: date_command
      run: |
       $date_str = Get-Date -format "hh-mm_dd-MM-yyyy"
       echo ::set-output name=date_str::$( $date_str)
      shell: pwsh
    - name: Print
      run: echo ${{ steps.run.date_command.outputs.date_str }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
